# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: openhim-core
#   labels:
#     app: openhim-core
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: openhim-core
#   template:
#     metadata:
#       labels:
#         app: openhim-core
#     spec:
#       containers:
#       - name: openhim-core
#         image: jembi/openhim-core:v7.2.1
#         env:
#         - name: mongo_url
#           value: "mongodb+srv://doadmin:1EVT8W920Y4ldg65@mongodb-a2b3c3cd.mongo.ondigitalocean.com/openhimdb?replicaSet=mongodb&tls=true&authSource=admin"
#         - name: mongo_atnaUrl
#           value: "mongodb+srv://doadmin:1EVT8W920Y4ldg65@mongodb-a2b3c3cd.mongo.ondigitalocean.com/openhimdb?replicaSet=mongodb&tls=true&authSource=admin"
#         - name: NODE_ENV
#           value: "development"
#         - name: OPENHIM_SERVER_PORT
#           value: "8080"
#         ports:
#         - name: http
#           containerPort: 8080
#         - name: api
#           containerPort: 5000
#         - name: console
#           containerPort: 5001
        
# ---

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: openhim-console-default-config
# data:
#   default.json: |
#     {
#       "version": "1.10.0",
#       "minimumCoreVersion": "3.4.0",
#       "protocol": "https",
#       "host": "146.190.184.187",
#       "port": 8080,
#       "title": "Admin Console",
#       "footerTitle": "OpenHIM Administration Console",
#       "footerPoweredBy": "<a href='http://openhim.org/' target='_blank'>Powered by OpenHIM</a>",
#       "loginBanner": "ParallelScore OpenHim Console",
#       "mediatorLastHeartbeatWarningSeconds": 60,
#       "mediatorLastHeartbeatDangerSeconds": 120,
#       "showLoginForm": true,
#       "ssoEnabled": false,
#       "keyCloakUrl": "http://localhost:9088",
#       "keyCloakRealm": "platform-realm",
#       "keyCloakClientId": "openhim-oauth"
#     }

#   visualizer.json: |
#     {
#       "components": [],
#       "channels": [],
#       "mediators": [],
#       "color": {
#         "inactive": "#cccccc",
#         "active": "#4cae4c",
#         "error": "#d43f3a",
#         "text": "#000000"
#       },
#       "size": {
#         "responsive": true,
#         "width": 1000,
#         "height": 400,
#         "padding": 20
#       },
#       "time": {
#         "updatePeriod": 200,
#         "minDisplayPeriod": 500,
#         "maxSpeed": 5,
#         "maxTimeout": 5000
#       }
#     }

# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: openhim-console
#   labels:
#     app: openhim-console
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: openhim-console
#   template:
#     metadata:
#       labels:
#         app: openhim-console
#     spec:
#       volumes:
#         - name: openhim-console-default-config-volume
#           configMap:
#             name: openhim-console-default-config
#       containers:
#       - name: openhim-console
#         image: jembi/openhim-console:v1.16.2
#         volumeMounts:
#         - mountPath: /usr/share/nginx/html/config
#           name: openhim-console-default-config-volume
#         ports:
#         - name: http
#           containerPort: 80
#         livenessProbe:
#           httpGet:
#             path: /
#             port: http
#           initialDelaySeconds: 30
#           periodSeconds: 30
#         readinessProbe:
#           httpGet:
#             path: /
#             port: http
#           initialDelaySeconds: 10
#           periodSeconds: 10

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: openhim-core
# spec:
#   selector:
#     app: openhim-core
#   ports:
#   - name: http
#     port: 8080
#     targetPort: 8080
#   - name: api
#     port: 5000
#     targetPort: 5000
#   - name: socket
#     port: 5001
#     targetPort: 5001
#   type: LoadBalancer

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: openhim-console
# spec:
#   selector:
#     app: openhim-console
#   ports:
#   - name: http
#     port: 80
#     targetPort: 80


# ### OpenHim Console Login credentials
# # Email:    root@openhim.org
# # password: N8QajOvU979Yq7U6
# # URL:      https://lafiaopenhim.parallelscoreprojects.com