# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: keycloak
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: keycloak
#   template:
#     metadata:
#       labels:
#         app: keycloak
#     spec:
#       containers:
#       - name: keycloak
#         image: quay.io/keycloak/keycloak:21.0.2
#         args: ["start-dev"]
#         env:
#         - name: DB_VENDOR
#           value: POSTGRES
#         - name: DB_ADDR
#           value: keycloak-postgres
#         - name: DB_PORT
#           value: "5432"
#         - name: DB_DATABASE
#           value: keycloak
#         - name: DB_USER
#           valueFrom:
#             secretKeyRef:
#               name: keycloak-postgres-credentials
#               key: POSTGRES_USER
#         - name: DB_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: keycloak-postgres-credentials
#               key: POSTGRES_PASSWORD
#         - name: KEYCLOAK_ADMIN
#           value: parallelscore
#         - name: KEYCLOAK_ADMIN_PASSWORD
#           value: Key@#admin78!/
#         - name: KC_HTTP_ENABLED
#           value: "true"
#         - name: KEYCLOAK_HTTP_PORT
#           value: "8080"
#         - name: KEYCLOAK_HTTPS_PORT
#           value: "8443"
#         - name: KEYCLOAK_FRONTEND_URL
#           value: "https://keycloak.lafia.io"
#         - name: KC_PROXY
#           value: "passthrough"
#         ports:
#         - name: http
#           containerPort: 8080
#         - name: https
#           containerPort: 8443
#         readinessProbe:
#           httpGet:
#             path: /realms/master
#             port: 8080
#           initialDelaySeconds: 60
#           periodSeconds: 1
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: keycloak
# spec:
#   selector:
#     app: keycloak
#   ports:
#   - name: https
#     port: 80
#     targetPort: 8080